'use client'

import React, { useState } from 'react'

const faqs = [
  {
    q: 'How long does setup take?',
    a: 'Most clients are fully live within 7–14 days of signing. We handle everything — you just need to answer a short onboarding questionnaire so we can tailor the automation to your business.',
  },
  {
    q: 'What kinds of businesses do you work with?',
    a: 'We specialize in local service businesses: dental practices, med spas, gyms, real estate agents, contractors, and law firms. If you have customers in a specific geography, we can generate and convert leads for you.',
  },
  {
    q: 'Do I need any tech skills?',
    a: 'None at all. You get a clean client portal where you can see leads, reports, and automations. Everything else runs behind the scenes. No setup required from your end beyond our onboarding form.',
  },
  {
    q: 'What is the difference between the plans?',
    a: 'Starter includes 1–2 services and up to 50 leads/month. Growth includes 3–4 services and up to 200 leads/month with priority support. Scale includes all 5 services, unlimited leads, an AI support agent, and a quarterly strategy call.',
  },
  {
    q: 'Can I cancel at any time?',
    a: 'Yes. There are no long-term contracts. We ask for 30 days notice before cancelling your subscription. The setup fee is non-refundable as it covers the work to build your automation stack.',
  },
  {
    q: 'How does the lead generation actually work?',
    a: 'We use the Google Places API to identify businesses in your target niches and cities daily. Each lead is scored on factors like review count, rating, and website presence — so you receive ranked, actionable prospects, not a raw list.',
  },
  {
    q: 'How are the AI follow-up emails personalized?',
    a: 'Every email is generated by Claude, Anthropic\'s AI model, using the specific business name, category, and pain signals we found during research. Emails are plain-text style for higher deliverability and conversions.',
  },
  {
    q: 'What happens after someone replies to an outreach email?',
    a: 'We detect replies automatically. The lead is moved to "Contacted" in your dashboard and removed from the automated sequence. You take it from there — the AI has done the heavy lifting.',
  },
  {
    q: 'Is this compliant with CAN-SPAM and GDPR?',
    a: 'Yes. Every outreach email includes an unsubscribe link, and all unsubscribes are processed automatically and permanently. We recommend reviewing the spec with your legal team if you operate in regulated industries.',
  },
  {
    q: 'What is included in the weekly report?',
    a: 'Each Monday you receive an AI-written report covering: leads generated, emails sent, open and reply rates, reviews collected, and a forward-looking recommendation for the week. It\'s written in plain English — no dashboards to decode.',
  },
]

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  return (
    <section id="faq" className="py-32 bg-navy-light">
      <div className="max-w-3xl mx-auto px-6">
        <div className="text-center mb-16">
          <p className="text-accent font-semibold text-sm uppercase tracking-widest mb-4">FAQ</p>
          <h2 className="text-4xl md:text-5xl font-bold text-cream">Common questions</h2>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <div
              key={i}
              className="bg-navy border border-white/[0.06] rounded-xl overflow-hidden"
            >
              <button
                className="w-full flex items-center justify-between px-6 py-5 text-left group"
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
              >
                <span className="font-medium text-cream group-hover:text-cream/90 pr-4 text-sm md:text-base">
                  {faq.q}
                </span>
                <svg
                  className={`w-5 h-5 text-cream/40 flex-shrink-0 transition-transform duration-200 ${
                    openIndex === i ? 'rotate-45' : ''
                  }`}
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                </svg>
              </button>
              {openIndex === i && (
                <div className="px-6 pb-5">
                  <p className="text-cream/60 text-sm leading-relaxed">{faq.a}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
